# Generated by Django 4.2.11 on 2024-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("payment", "Payment"), ("charge", "Charge")],
                default="payment",
                max_length=10,
            ),
        ),
    ]
