# Generated by Django 4.2.11 on 2024-03-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
